### ISSUE TITLE
Add to F-Droid?

### ISSUE THREAD

**Issue by picsi** [Limegrass/Wanicchou#10]
It'd be neat to have this on F-Droid, as there's currently no Japanese to Japanese dictionary there: https://f-droid.org/

If you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by Limegrass** [comment]
I'll throw it on there, but I haven't worked on it in a little bit since I was working on my website. I might be doing a bit more work there before coming back to this and looking at where I left off. I believe there was at least some cleanup I wanted to do before any type of App Store release. Thanks for using the app!

**Comment by picsi** [comment]
I've opened a request for it here: https://gitlab.com/fdroid/rfp/issues/633

**Comment by Limegrass** [comment]
I believe it is mostly acceptable for an initial beta release. I have not looked into the release process for F-Droid, but I would not mind having someone else do it if it is fairly complicated.

I will look into the process over the next few days, but I will be working, and it may be slow if it's complicated.

Assuming you (or someone else) does it for me, I assume the only releases on F-Droid will be the releases on GitHub?

**Comment by picsi** [comment]
Correct! F-Droid should automatically pick up your releases

Pinging @rudloff

**Comment by Limegrass** [comment]
Sounds great, thanks!

**Comment by Rudloff** [comment]
@Limegrass I see all your releases have the same version code (1) and version name (1.0). You need to increase the version code for each release or users won't be able to update the app correctly.

**Comment by Limegrass** [comment]
Oh right, sorry about that, I didn't intend for any formal release until I had fully implemented all the basic aspects I had in mind. Should I go through and increment the release number for all the old releases, or will it be sufficient to re-release the current version and then continue from this point on incrementing the version code and name?

**Comment by Limegrass** [comment]
@Rudloff Sorry, I should have pinged earlier. I hope that everything is all ready for you this time.

**Comment by Rudloff** [comment]
Everything is OK.
I submitted a [request](https://gitlab.com/fdroid/fdroiddata/merge_requests/3440) that needs to be reviewed by another F-Droid contributor.

**Comment by picsi** [comment]
@Limegrass a question has come up, can you clarify?

https://gitlab.com/fdroid/fdroiddata/merge_requests/3440#note_93046012
